
package Vistas;

import javax.swing.JFrame;


public class MenuPrincipal extends javax.swing.JFrame {


    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Gestión de Paquetes Turísticos");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmPrincipal = new javax.swing.JMenu();
        jmTuristas = new javax.swing.JMenuItem();
        jmCiudades = new javax.swing.JMenuItem();
        jmTransportes = new javax.swing.JMenuItem();
        jmAlojamientos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmPresupuestos = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 897, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );

        jmPrincipal.setText("Menu Principal");

        jmTuristas.setText("Turistas");
        jmTuristas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTuristasActionPerformed(evt);
            }
        });
        jmPrincipal.add(jmTuristas);

        jmCiudades.setText("Ciudades - Temporadas ");
        jmCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCiudadesActionPerformed(evt);
            }
        });
        jmPrincipal.add(jmCiudades);

        jmTransportes.setText("Transportes");
        jmTransportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTransportesActionPerformed(evt);
            }
        });
        jmPrincipal.add(jmTransportes);

        jmAlojamientos.setText("Alojamientos");
        jmAlojamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlojamientosActionPerformed(evt);
            }
        });
        jmPrincipal.add(jmAlojamientos);

        jMenuBar1.add(jmPrincipal);

        jMenu1.setText("Paquetes Turisticos");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmPresupuestos.setText("Confeccionar Presupuesto");
        jmPresupuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPresupuestosActionPerformed(evt);
            }
        });
        jMenu1.add(jmPresupuestos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCiudadesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormCiudades ciudades= new FormCiudades();
        ciudades.setVisible(true);
        escritorio.add(ciudades);
        escritorio.moveToBack(ciudades);
    }//GEN-LAST:event_jmCiudadesActionPerformed

    private void jmTransportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTransportesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormTransportes transportes= new FormTransportes();
        transportes.setVisible(true);
        escritorio.add(transportes);
        escritorio.moveToFront(transportes);
    }//GEN-LAST:event_jmTransportesActionPerformed


    private void jmTuristasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTuristasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormTurista turista= new FormTurista();
        turista.setVisible(true);
        escritorio.add(turista);
        escritorio.moveToFront(turista);
    }//GEN-LAST:event_jmTuristasActionPerformed


    private void jmAlojamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlojamientosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormAlojamientos alojamientos = new FormAlojamientos();
        alojamientos.setVisible(true);
        escritorio.add(alojamientos);
        escritorio.moveToFront(alojamientos);
        
        
    }//GEN-LAST:event_jmAlojamientosActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmPresupuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPresupuestosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormVentaPaquetes paquetes = new FormVentaPaquetes();
        paquetes.setVisible(true);
        escritorio.add(paquetes);
        escritorio.moveToFront(paquetes);
    }//GEN-LAST:event_jmPresupuestosActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmAlojamientos;
    private javax.swing.JMenuItem jmCiudades;
    private javax.swing.JMenuItem jmPresupuestos;
    private javax.swing.JMenu jmPrincipal;
    private javax.swing.JMenuItem jmTransportes;
    private javax.swing.JMenuItem jmTuristas;
    // End of variables declaration//GEN-END:variables
}
